plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "crafting-mats-fabric-$minecraft_version"
}

repositories {
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent { // Sable
        forRepository {
            maven {
                url = "https://maven.ryanhcode.dev/releases"
                name = "RyanHCode Maven"
            }
        }
        filter {
            includeGroup("dev.ryanhcode.sable")
            includeGroup("dev.ryanhcode.sable-companion")
        }
    }
    maven { // Veil
        name = "BlameJared Maven"
        url = "https://maven.blamejared.com"
    }
    maven { // Forge Config API port
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    if(true) { // MacOS Dev Tweaks
        modRuntimeOnly "maven.modrinth:ctrl-q:N4g6q0kL"
        modRuntimeOnly "maven.modrinth:mcmouser:1.21-fabric-1.0.0"
    }

    // Sable
    modCompileOnlyApi("dev.ryanhcode.sable:sable-fabric-${project.minecraft_version}:${project.sable_version}")

    if(sable_enabled) {
        modRuntimeOnly("foundry.veil:veil-fabric-${project.minecraft_version}:${project.veil_version}") {
            exclude group: "maven.modrinth"
        }

        modRuntimeOnly("dev.ryanhcode.sable:sable-fabric-${project.minecraft_version}:${project.sable_version}")
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

processResources {
    inputs.property "version", version
    inputs.property "mod_name", mod_name
    inputs.property "mod_id", mod_id
    inputs.property "description", description

    filesMatching("fabric.mod.json") {
        expand(
            "version": version,
            "mod_name": mod_name,
            "mod_id": mod_id,
            "description": description
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
