org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

## Mod Properties
mod_id=crafting_mats
mod_name=Crafting Mats
mod_license=MIT
mod_version=1.0.1
mod_group_id=net.vercte.craftingmats
mod_authors=Vercte
mod_description=Turn any block into a crafting table.

## Mod Dependencies
fabric_api_version=0.116.12+1.21.1
veil_version=4.0.0
sable_version=1.2.2
sable_enabled=false